FROM debian:13-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    git \
    meson \
    python3 \
    pkg-config \
    libssl-dev \
    libasio-dev \
    ca-certificates \
    libpq-dev \
    libpqxx-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["bash"]